import { DateTime } from 'ionic-angular';
export class OrderDetailsWorkflow {
    public Id_Processo_Lavorazione: number;
    public IdOrder?: number;
    public NumeroOrdine: string; 
    public Id_Order_Dettail?: number;
    public Id_Gruppo?: number;
    public Nome_Gruppo: string;
    public Tipo_Processo?: number;
    public Nome_Processo: string; 
    public Stato_Processo? : number; 
    public DataAssegnazione_Processo?: DateTime;
    public DataInizio_Processo?: DateTime;
    public DataFine_Processo?: DateTime;
    public DataAnnullamento_Processo?: DateTime;
    public NoteAnnullamento_Processo: string; 
    public Inizio_Processo_Operatore: string; 
    public Fine_Processo_Operatore: string; 
    public Annulla_Processo_Operatore: string; 
    public SSMA_TimeStamp: any; 
    public IdOperatore?: number; 
    public PosizioneProcesso?: number; 
    public Sospeso_Processo_Operatore: string;
    public Note_Sospensione_Processo: string;
    public Id_Attivita?: number; 
    public Id_Fase?: number; 
    public Nome_Fase: string;
    public Id_Reparto?: number; 
    public Nome_Reparto: string; 
    public Id_Workflow?: number; 
    public Nome_Workflow: string; 
    public Ordine_Fase?: number; 
    public Id_Elemento?: number; 
    public Descrizione_Elemento: string; 
    public DataScadenzaOrdine?: DateTime; 
    public IdCliente?: number; 
    public IdOperatori: string; 
}